baseURL = "https://ok-datahub.netlify.app/"
languageCode = "en-us"
title = "Oklahoma Data Hub"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = false # show / hide the contaxt box on the homepage
    show_services_button = false  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo-mobile.png"
    mobile_height = "36px"
    desktop = "images/logo/ok_datahub.png"
    desktop_height = "50px"
    alt = "OK Data Hub - State and County Indicators in Oklahoma"

  [params.seo]
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = ''

[menu]
  # Main Menu
  [[menu.main]]
    name = "Access the Data"
    url = "/services/"
      weight = 1

#  [[menu.main]]
#      name = "Team"
#      url = "/team/"
#      weight = 2

#  [[menu.main]]
#      name = "About"
#      url = "/about/"
#      weight = 3

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 4

  # Footer Menu
  [[menu.footer]]
  name = "About"
  url = "/about/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
